version: 2
jobs:
  build:
    docker:
      - image: python
    working_directory: ~/repo
    steps:
      - checkout
      # Bundle install dependencies
      - run: pip install -r requirements.txt

      # Database setup
      - run: python test

  deploy:
    docker:
      - image: python
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: sequential-branch-filter
